SPK_NAME = iperf3
SPK_VERS = 3.9
SPK_REV = 2
SPK_ICON = src/iperf3.png

DEPENDS = cross/$(SPK_NAME)

MAINTAINER = 杨康
DESCRIPTION = iperf系列工具执行主动测量，以确定IP网络上可达到的最大带宽。它支持与定时、协议和缓冲区相关的各种参数的调优。对于每个测试，它报告测量的吞吐量、损耗和其他参数。
DISPLAY_NAME = iperf3
STARTABLE = no

HOMEPAGE = https://iperf.fr/
LICENSE = 3-clause BSD

SPK_COMMANDS = bin/iperf3

include ../../mk/spksrc.spk.mk
